import Link from "next/link";
import { PrintButton } from "@/components/app/PrintButton";
import { fmtDate } from "@/lib/dates";

/** Print-friendly wrapper for a generated report. */
export function ReportShell({
  title,
  subtitle,
  orgName,
  children,
}: {
  title: string;
  subtitle?: string;
  orgName?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mx-auto max-w-3xl">
      <div className="mb-6 flex items-center justify-between print:hidden">
        <Link href="/dashboard/reports" className="text-sm text-slate hover:text-ink">
          ← Reports
        </Link>
        <PrintButton />
      </div>
      <div className="rounded-lintel border border-hairline bg-surface p-8 print:border-0 print:p-0">
        <header className="mb-6 border-b border-hairline pb-4">
          <h1 className="font-heading text-2xl font-semibold tracking-tight text-ink">{title}</h1>
          <p className="mt-1 text-sm text-slate">
            {orgName ? `${orgName} · ` : ""}
            {subtitle ? `${subtitle} · ` : ""}
            generated {fmtDate(new Date())} by Lintel
          </p>
        </header>
        {children}
        <footer className="mt-8 border-t border-hairline pt-4 text-xs text-slate">
          Generated by Lintel from your records. Indicative — not legal advice.
        </footer>
      </div>
    </div>
  );
}
